# This pyproject.toml file has unpinned dependencies - meaning it's suitable
# for local development, CI runs, building packaging artifacts (wheels, conda
# packages, rpm/deb/etc. Linux packages, and so on) for arbitrary end user and
# packaging systems.
# It is NOT SUITABLE to use directly for producing sdist/wheels to upload to
# PyPI. Use the `tools/build-pypi-artifacts.py` script for that.
#
# Also important: meson-python uses `meson dist` under the hood, meaning that
# changes to files that are not committed do not end up in the sdist/wheel!

# Note that in maintenance branches, all build dependencies should
# have an upper bound equal to the most recent already-released version
# of the dependency. This to prevent that a future backwards-incompatible
# release will break the source build of a SciPy release.
# Do accept micro (bug-fix) releases. So for example, if pybind11 2.4.3 is
# the most recent version on PyPI:
#
#     "pybind11>=2.4.3,<2.5.0",

[build-system]
build-backend = 'mesonpy'
requires = [
    "meson-python>=0.4.0",
    "Cython>=0.29.18",
    "pybind11>=2.4.3",
    "pythran>=0.9.12",
    "numpy>=1.18.5",
]

[project]
name = "SciPy"
license = {file = "LICENSE.txt"}
description = """
SciPy (pronounced "Sigh Pie") is an open-source software for mathematics,
science, and engineering. It includes modules for statistics, optimization,
integration, linear algebra, Fourier transforms, signal and image processing,
ODE solvers, and more.
"""

maintainers = [
    {name = "SciPy Developers", email = "scipy-dev@python.org"},
]
# Note: Python and NumPy upper version bounds should be set correctly in
# release branches, see:
#     https://scipy.github.io/devdocs/dev/core-dev/index.html#version-ranges-for-numpy-and-other-dependencies
requires-python = ">=3.8"
dependencies = [
    # TODO: update to "pin-compatible" once possible, see https://github.com/FFY00/meson-python/issues/29
    "numpy>=1.18.5",
]
readme = "README.rst"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: C",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Software Development :: Libraries",
    "Topic :: Scientific/Engineering",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Operating System :: MacOS",
]
dynamic = ['version']

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "pytest-xdist",
    "asv",
    "mpmath",
    "gmpy2",
    "threadpoolctl",
    "scikit-umfpack",
]
doc = [
    "sphinx!=3.1.0, !=4.1.0",
    "pydata-sphinx-theme>=0.8.1",
    "sphinx-panels>=0.5.2",
    "matplotlib>2",
    "numpydoc",
    "sphinx-tabs",
]
dev = [
    "mypy",
    "typing_extensions",
    "pycodestyle",
    "flake8",
]

[project.urls]
homepage = "https://scipy.org/"
documentation = "https://docs.scipy.org/doc/scipy/"
source = "https://github.com/scipy/scipy"
download = "https://github.com/scipy/scipy/releases"
tracker = "https://github.com/scipy/scipy/issues"


[tool.doit]
dodoFile = "do.py"

